/*
 * Copyright (C) 2013-2014 Freescale Semiconductor, Inc.
 *
 * Author: Fabio Estevam <fabio.estevam@freescale.com>
 *
 * Copyright (C) 2014 O.S. Systems Software LTDA.
 *
 * Author: Otavio Salvador <otavio@ossystems.com.br>
 *
 * Copyright (C) 2014 Kynetics, LLC
 *
 * Backport to 2013.04: Diego Rondini
 *
 * Copyright (C) 2014 Revolution Robotics, Inc.
 *
 * Author: Jacob Postman <jacob@revolution-robotics.com>
 *
 * SPDX-License-Identifier:    GPL-2.0+
 */
#ifndef WARP_COMMON
#define WARP_COMMON

#include <asm/arch/mx6-pins.h>
#include <asm/imx-common/iomux-v3.h>

//#define DEBUG_SSD2805

#define LCD_PAD_CTRL   ( PAD_CTL_SPEED_HIGH | PAD_CTL_DSE_80ohm |      \
	PAD_CTL_SRE_FAST | PAD_CTL_LVE)

#define PINID_LCD_DAT0		IMX_GPIO_NR(2, 20)
#define PINID_LCD_DAT1		IMX_GPIO_NR(2, 21)
#define PINID_LCD_DAT2		IMX_GPIO_NR(2, 22)
#define PINID_LCD_DAT3		IMX_GPIO_NR(2, 23)
#define PINID_LCD_DAT4		IMX_GPIO_NR(2, 24)
#define PINID_LCD_DAT5		IMX_GPIO_NR(2, 25)
#define PINID_LCD_DAT6		IMX_GPIO_NR(2, 26)
#define PINID_LCD_DAT7		IMX_GPIO_NR(2, 27)
#define PINID_LCD_DAT8		IMX_GPIO_NR(2, 28)
#define PINID_LCD_DAT9		IMX_GPIO_NR(2, 29)
#define PINID_LCD_DAT10		IMX_GPIO_NR(2, 30)
#define PINID_LCD_DAT11		IMX_GPIO_NR(2, 31)
#define PINID_LCD_DAT12		IMX_GPIO_NR(3, 0)
#define PINID_LCD_DAT13		IMX_GPIO_NR(3, 1)
#define PINID_LCD_DAT14		IMX_GPIO_NR(3, 2)
#define PINID_LCD_DAT15		IMX_GPIO_NR(3, 3)

#define PINID_LCD_RS		IMX_GPIO_NR(2, 19)
#define PINID_LCD_CS		IMX_GPIO_NR(2, 17)
#define PINID_LCD_RD		IMX_GPIO_NR(3, 11)
#define PINID_LCD_WR		IMX_GPIO_NR(2, 15)

#define PINID_MIPI_TE		IMX_GPIO_NR(3, 4)
#define PINID_LCD_RSTN 		IMX_GPIO_NR(3, 7)
#define PINID_LCD_INTN		IMX_GPIO_NR(3, 8)
#define PINID_MIPI_BSYNC	IMX_GPIO_NR(3, 9)
#define PINID_MIPI_RSTN		IMX_GPIO_NR(3, 10)

// PWM CLK output frequency
#define MIPI_CLK_FREQ		33300000

#  define LCDIF_SLOW_FREQDIV	250
#  define LCDIF_FAST_FREQDIV	20
#  define LCDIF_BUS_WIDTH	8
#  define SSD2805_PLL_CLK_FREQ	200000000

static iomux_v3_cfg_t const mcu8080display_pads[] = {
	MX6_PAD_LCD_DAT0__LCDIF_DAT_0 | MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX6_PAD_LCD_DAT1__LCDIF_DAT_1 | MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX6_PAD_LCD_DAT2__LCDIF_DAT_2 | MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX6_PAD_LCD_DAT3__LCDIF_DAT_3 | MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX6_PAD_LCD_DAT4__LCDIF_DAT_4 | MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX6_PAD_LCD_DAT5__LCDIF_DAT_5 | MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX6_PAD_LCD_DAT6__LCDIF_DAT_6 | MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX6_PAD_LCD_DAT7__LCDIF_DAT_7 | MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX6_PAD_LCD_DAT8__LCDIF_DAT_8 | MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX6_PAD_LCD_DAT9__LCDIF_DAT_9 | MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX6_PAD_LCD_DAT10__LCDIF_DAT_10 | MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX6_PAD_LCD_DAT11__LCDIF_DAT_11 | MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX6_PAD_LCD_DAT12__LCDIF_DAT_12 | MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX6_PAD_LCD_DAT13__LCDIF_DAT_13 | MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX6_PAD_LCD_DAT14__LCDIF_DAT_14 | MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX6_PAD_LCD_DAT15__LCDIF_DAT_15 | MUX_PAD_CTRL(LCD_PAD_CTRL),
	// GPIO for LCD_RDX(SSD)/LCD_RD_E(IMX) future rev may switch to hardware LCDIF_RD_E
	MX6_PAD_LCD_DAT23__GPIO_3_11 | MUX_PAD_CTRL(LCD_PAD_CTRL),	// LCD_RDX(SSD)/LCD_RD_E(MX6_Signal)
	MX6_PAD_LCD_CLK__LCDIF_WR_RWN | MUX_PAD_CTRL(LCD_PAD_CTRL),	// LCD_WRX(SSD)/LCD_WR_RWn(MX6_Signal)/
	MX6_PAD_LCD_HSYNC__LCDIF_CS | MUX_PAD_CTRL(LCD_PAD_CTRL), 	// LCD_CSX(SSD)/LCD_CS(MX6_Signal)
	// LCD_RESET as GPIO for LCD_DCX(SSD)/LCD_RS(IMX) future rev may switch to hardware LCDIF_RS
	MX6_PAD_LCD_RESET__GPIO_2_19 | MUX_PAD_CTRL(LCD_PAD_CTRL), 	// LCD_DCX(SSD) LCD_RS(IMX)
	//MX6_PAD_AUD_TXFS__PWM3_PWMO | MUX_PAD_CTRL(LCD_PAD_CTRL),	// temp pwm output test to pad
	//MX6_PAD_AUD_TXFS__GPIO_1_4 | MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX6_PAD_AUD_MCLK__PWM4_PWMO | MUX_PAD_CTRL(LCD_PAD_CTRL),	// LCD_CLK
	MX6_PAD_LCD_DAT16__GPIO_3_4 | MUX_PAD_CTRL(LCD_PAD_CTRL),	// MIPI_TE
	MX6_PAD_LCD_DAT19__GPIO_3_7 | MUX_PAD_CTRL(LCD_PAD_CTRL),	// LCD_RSTn
	MX6_PAD_LCD_DAT20__GPIO_3_8 | MUX_PAD_CTRL(LCD_PAD_CTRL),	// LCD_INTn
	MX6_PAD_LCD_DAT21__GPIO_3_9 | MUX_PAD_CTRL(LCD_PAD_CTRL),	// MIPI_B_SYNC
	MX6_PAD_LCD_DAT22__GPIO_3_10 | MUX_PAD_CTRL(LCD_PAD_CTRL),	// MIPI_RSTn
	// LCDIF_RD_E not currently used. For future rev this may be used for LCD_RDX(SSD)/LCD_RD_E(IMX6)

};

static iomux_v3_cfg_t const pwm_pads[] = {
	MX6_PAD_AUD_TXFS__PWM3_PWMO | MUX_PAD_CTRL(LCD_PAD_CTRL),	// temp pwm output test to pad
	MX6_PAD_AUD_MCLK__PWM4_PWMO | MUX_PAD_CTRL(LCD_PAD_CTRL),	// LCD_CLK
};

#endif // WARP_COMMON
